### PR TITLE
Add api wrappers

### PR DESCRIPTION
**Pull request by robbarnsley**
Amended Dockerfile to add prerequisite packages (gfal, cmake etc.) for the rucio-clients python package.

Rucio logic is now contained within rucio_wrappers.py to stop name conflict with rucio-clients module. Inside rucio_wrappers there are now two classes derived from an abstract base class RucioWrappers: RucioWrappersAPI and RucioWrappersCLI. These have a host of static methods that should be functionally interchangeable (same function prototypes).

Should now have all the necessary API calls to do the second injection test.

Not tested thoroughly, but ran a few calls to check they work, e.g.

```python
from rucio_wrappers import RucioWrappersAPI

r = RucioWrappersAPI()

client = r.addDataset("SKA_SKAO_BARNSLEY-testing:test-dataset-1")
client = r.upload('DESY-DCACHE', 'SKA_SKAO_BARNSLEY-testing', 'test', 3600)
r.addRule('SKA_SKAO_BARNSLEY-testing:test', 1, 'ALPAMED-DPM', lifetime=3600)
res = r.attach('SKA_SKAO_BARNSLEY-testing:test-dataset-1', 'SKA_SKAO_BARNSLEY-testing:test')
res = r.detach('SKA_SKAO_BARNSLEY-testing:test-dataset-1', 'SKA_SKAO_BARNSLEY-testing:test)

print(r.listDIDs('SKA_SKAO_BARNSLEY-testing', filters="type=ALL"))
print(r.listFileReplicas('SKA_SKAO_BARNSLEY-testing:test'))
print(r.listReplicationRulesFull('SKA_SKAO_BARNSLEY-testing:test'))
print(r.listReplicationRules('SKA_SKAO_BARNSLEY-testing:test'))

r.erase('SKA_SKAO_BARNSLEY-testing:test')
```

### CODE REVIEW

**Comment by JColl88** [comment]
Rebuilding the Docker image threw an error - it was unable to install the gfal2-python package, possibly due to incorrect version of CMake - will send you the full error tomorrow

**Comment by robbarnsley** [comment]
apparently I keep putting commas between packages in yum installs (which breaks it).

should be fixed now.

**Comment by robbarnsley** [comment]
removed gfal2 dependencies from Dockerfile as they're now installed upstream via the base image

**Review by JColl88 — APPROVED** [review]
All looks good!

**Pull request merged**
